### ISSUE TITLE
libpthread.so.0: undefined symbol: _dl_make_stack_executable

### ISSUE THREAD

**Issue by zhuck163** [greatsql/GreatSQL#10]
【操作系统】
5.10.0-60.18.0.50.h1083.eulerosv2r11.x86_64
【GreatSQL-Shell版本】
greatsql-shell-8.0.32-25-glibc2.28-x86_64.tar.xz
安装后执行mysqlsh后报错

[root@9f074625698c bin]# ./mysqlsh 
**./mysqlsh: symbol lookup error: /usr/local/mysqlsh/bin/../lib/mysqlsh/libpthread.so.0: undefined symbol: _dl_make_stack_executable, version GLIBC_PRIVATE**
[root@9f074625698c bin]# strings /usr/local/mysqlsh/bin/../lib/mysqlsh/libpthread.so.0 |grep _dl_make_stack_executable
**_dl_make_stack_executable
_dl_make_stack_executable@@GLIBC_PRIVATE**
[root@9f074625698c bin]# ldd mysqlsh 
        linux-vdso.so.1 (0x00007ffe40513000)
        libpthread.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpthread.so.0 (0x00007faeaba8d000)
        libdl.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libdl.so.2 (0x00007faeab889000)
        libssl.so.1.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libssl.so.1.1 (0x00007faeab5f5000)
        libcrypto.so.1.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcrypto.so.1.1 (0x00007faeab10c000)
        libresolv.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libresolv.so.2 (0x00007faeaaef5000)
        librt.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/librt.so.1 (0x00007faeaaced000)
        libprotobuf.so.30 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libprotobuf.so.30 (0x00007faeaa845000)
        libssh.so.4 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libssh.so.4 (0x00007faeaa5d6000)
        libutil.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libutil.so.1 (0x00007faeaa3d2000)
        libcurl.so.4 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcurl.so.4 (0x00007faeaa14e000)
        libnode.so.93 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libnode.so.93 (0x00007faea6a0b000)
        libpython3.8.so.1.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpython3.8.so.1.0 (0x00007faea6473000)
        libm.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libm.so.6 (0x00007faea60ef000)
        libantlr4-runtime.so.4.10 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libantlr4-runtime.so.4.10 (0x00007faea5ddd000)
        libstdc++.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libstdc++.so.6 (0x00007faea5a48000)
        libgcc_s.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libgcc_s.so.1 (0x00007faea5830000)
        libc.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libc.so.6 (0x00007faea546b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faeabcaf000)
        libz.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libz.so.1 (0x00007faea5254000)
        libgssapi_krb5.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libgssapi_krb5.so.2 (0x00007faea4ffd000)
        libkrb5.so.3 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkrb5.so.3 (0x00007faea4d13000)
        libk5crypto.so.3 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libk5crypto.so.3 (0x00007faea4afc000)
        libcom_err.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcom_err.so.2 (0x00007faea48f8000)
        libnghttp2.so.14 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libnghttp2.so.14 (0x00007faea46d0000)
        libuv.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libuv.so.1 (0x00007faea449e000)
        libbrotlidec.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlidec.so.1 (0x00007faea4291000)
        libbrotlienc.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlienc.so.1 (0x00007faea4005000)
        libcrypt.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcrypt.so.1 (0x00007faea3ddc000)
        libuuid.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libuuid.so.1 (0x00007faea3bd4000)
        libkrb5support.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkrb5support.so.0 (0x00007faea39c1000)
        libkeyutils.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkeyutils.so.1 (0x00007faea37bd000)
        libbrotlicommon.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlicommon.so.1 (0x00007faea359c000)
        libselinux.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libselinux.so.1 (0x00007faea3372000)
        libpcre2-8.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpcre2-8.so.0 (0x00007faea30ee000)

另：同服务上安装mysql-shell-8.0.38-linux-glibc2.28-x86-64bit，可正常使用

**Comment by GreatSQL** [comment]
> 【操作系统】 5.10.0-60.18.0.50.h1083.eulerosv2r11.x86_64 【GreatSQL-Shell版本】 greatsql-shell-8.0.32-25-glibc2.28-x86_64.tar.xz 安装后执行mysqlsh后报错
> 
> [root@9f074625698c bin]# ./mysqlsh **./mysqlsh: symbol lookup error: /usr/local/mysqlsh/bin/../lib/mysqlsh/libpthread.so.0: undefined symbol: _dl_make_stack_executable, version GLIBC_PRIVATE** [root@9f074625698c bin]# strings /usr/local/mysqlsh/bin/../lib/mysqlsh/libpthread.so.0 |grep _dl_make_stack_executable **_dl_make_stack_executable _dl_make_stack_executable@@GLIBC_PRIVATE** [root@9f074625698c bin]# ldd mysqlsh linux-vdso.so.1 (0x00007ffe40513000) libpthread.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpthread.so.0 (0x00007faeaba8d000) libdl.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libdl.so.2 (0x00007faeab889000) libssl.so.1.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libssl.so.1.1 (0x00007faeab5f5000) libcrypto.so.1.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcrypto.so.1.1 (0x00007faeab10c000) libresolv.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libresolv.so.2 (0x00007faeaaef5000) librt.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/librt.so.1 (0x00007faeaaced000) libprotobuf.so.30 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libprotobuf.so.30 (0x00007faeaa845000) libssh.so.4 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libssh.so.4 (0x00007faeaa5d6000) libutil.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libutil.so.1 (0x00007faeaa3d2000) libcurl.so.4 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcurl.so.4 (0x00007faeaa14e000) libnode.so.93 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libnode.so.93 (0x00007faea6a0b000) libpython3.8.so.1.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpython3.8.so.1.0 (0x00007faea6473000) libm.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libm.so.6 (0x00007faea60ef000) libantlr4-runtime.so.4.10 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libantlr4-runtime.so.4.10 (0x00007faea5ddd000) libstdc++.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libstdc++.so.6 (0x00007faea5a48000) libgcc_s.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libgcc_s.so.1 (0x00007faea5830000) libc.so.6 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libc.so.6 (0x00007faea546b000) /lib64/ld-linux-x86-64.so.2 (0x00007faeabcaf000) libz.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libz.so.1 (0x00007faea5254000) libgssapi_krb5.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libgssapi_krb5.so.2 (0x00007faea4ffd000) libkrb5.so.3 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkrb5.so.3 (0x00007faea4d13000) libk5crypto.so.3 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libk5crypto.so.3 (0x00007faea4afc000) libcom_err.so.2 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcom_err.so.2 (0x00007faea48f8000) libnghttp2.so.14 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libnghttp2.so.14 (0x00007faea46d0000) libuv.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libuv.so.1 (0x00007faea449e000) libbrotlidec.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlidec.so.1 (0x00007faea4291000) libbrotlienc.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlienc.so.1 (0x00007faea4005000) libcrypt.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libcrypt.so.1 (0x00007faea3ddc000) libuuid.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libuuid.so.1 (0x00007faea3bd4000) libkrb5support.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkrb5support.so.0 (0x00007faea39c1000) libkeyutils.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libkeyutils.so.1 (0x00007faea37bd000) libbrotlicommon.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libbrotlicommon.so.1 (0x00007faea359c000) libselinux.so.1 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libselinux.so.1 (0x00007faea3372000) libpcre2-8.so.0 => /usr/local/mysqlsh/bin/./../lib/mysqlsh/libpcre2-8.so.0 (0x00007faea30ee000)
> 
> 另：同服务上安装mysql-shell-8.0.38-linux-glibc2.28-x86-64bit，可正常使用

感谢反馈，目前GreatSQL Shell对非glibc 2.28的环境兼容性的确支持不好，我们在以后会想办法解决。

现在可以先采用docker方式运行，参考 https://github.com/GreatSQL/GreatSQL-Docker/tree/master/GreatSQL-Shell
