### ISSUE TITLE
8.0.32 啥时候发布呀

### ISSUE THREAD

**Issue by pt-cc** [greatsql/GreatSQL#3]

**Comment by GreatSQL** [comment]
很快乐，乐观的话，最快下周就能出来

**Comment by pt-cc** [comment]
这周能出来不，不能出来就换别的方案了，快等不及了😄

**Comment by GreatSQL** [comment]
> 这周能出来不，不能出来就换别的方案了，快等不及了😄

下周一（2023.6.5）发布，首发在gitee（https://gitee.com/GreatSQL/GreatSQL/），烦请关注。

**Comment by GreatSQL** [comment]
Hi GreatSQL发布8.0.32-24新版本了，主要有增加并行load data、（逻辑 & CLONE）备份加密、MGR读写节点可绑定动态VIP、Oracle兼容扩展、审计日志增强等新特性，可以关注下哈 ：）
https://gitee.com/GreatSQL/GreatSQL-Doc/blob/master/relnotes/greatsql-803224/changes-greatsql-8-0-32-24-20230605.md

**Comment by GreatSQL** [comment]
已发布，关闭issue
