### ISSUE TITLE
mysqld debug version will core if the number of cpu cores is larger than 128

### ISSUE THREAD

**Issue by FateTHarlaown** [greatsql/GreatSQL#5]
<img width="1908" alt="greatsql core" src="https://github.com/GreatSQL/GreatSQL/assets/15060840/0ce63fde-b58b-422a-92e7-48a1e9c98c10">

system var 'thread_pool-size' has a default equal to cpu number, but it's max values is 128. We will get a core if the server has more than 128 cpu core.

**Comment by GreatSQL** [comment]
感谢反馈，已经报告给研发同学了，我们会尽快确认/修复。

**Comment by GreatSQL** [comment]
在最新发布的GreatSQL 8.0.32-26版本中已修复该问题

**Comment by GreatSQL** [comment]
在最新发布的GreatSQL 8.0.32-26版本中已修复该问题
