### ISSUE TITLE
The newest version  v8.0.32.25 faces compiling problem

### ISSUE THREAD

**Issue by physicszq** [greatsql/GreatSQL#6]
GreatSQL/GreatSQL/tree/master/storage/perfschema/ha_perfschema.cc: 92 aseerting fault 
       my modify:
       GreatSQL/storage/perfschema/pfs_dd_version.h:236  static const uint PFS_DD_VERSION = 80032;  <-- 80025

GreatSQL/sql/dd/info_schema/metadata.h: 242aseerting fault
       my modify:
       GreatSQL/sql/dd/info_schema/metadata.h:241     static const uint IS_DD_VERSION = 80030;          <-- 80023

**Comment by GreatSQL** [comment]
```
GreatSQL/storage/perfschema/pfs_dd_version.h:236 static const uint PFS_DD_VERSION = 80032; <-- 80025
```
请问您这个写法的意思是把 PFS_DD_VERSION = 80032 改成 80025吗，不是太理解

**Comment by physicszq** [comment]
> ```
> GreatSQL/storage/perfschema/pfs_dd_version.h:236 static const uint PFS_DD_VERSION = 80032; <-- 80025
> ```
> 
> 请问您这个写法的意思是把 PFS_DD_VERSION = 80032 改成 80025吗，不是太理解

对，改成后面的值就可以编译安装成功，直接装在主机上

**Comment by GreatSQL** [comment]
> > ```
> > GreatSQL/storage/perfschema/pfs_dd_version.h:236 static const uint PFS_DD_VERSION = 80032; <-- 80025
> > ```
> > 
> >   
> > 请问您这个写法的意思是把 PFS_DD_VERSION = 80032 改成 80025吗，不是太理解
> 
> 对，改成后面的值就可以编译安装成功，直接装在主机上

麻烦再提供下编译完整参数，以及在你环境下编译时报错的日志。

在我的编译文档（https://greatsql.cn/docs/8032-25/user-manual/4-install-guide/6-install-with-source-code.html）中的编译环境下是正常的，有区别的地方在于我的代码是直接下载打包好的，而不是用git clone的

**Comment by physicszq** [comment]
编译参数：
sudo cmake -DLDAP_LIBRARY="/usr/lib/x86_64-linux-gnu/libldap.so" -DLDAP_INCLUDE_DIR="/usr/include" .. \
-DDOWNLOAD_BOOST=1 \
-DWITH_BOOST=/opt/boost \
-DCMAKE_INSTALL_PREFIX=/usr/local/GreatSQL-8.0.25-16-Linux-glibc2.28-x86_64 \
-DWITH_ZLIB=bundled \
-DWITH_NUMA=ON \
-DCMAKE_EXE_LINKER_FLAGS="-ljemalloc" \
-DBUILD_CONFIG=mysql_release \
-DWITH_TOKUDB=OFF \
-DWITH_ROCKSDB=OFF \
-DMAJOR_VERSION=8 \
-DMINOR_VERSION=0 \
-DPATCH_VERSION=25 \
-DWITH_UNIT_TESTS=OFF \
-DWITH_NDBCLUSTER=OFF \
-DWITH_SSL=system \
-DWITH_SYSTEMD=ON \
-DWITH_LDAP=OFF \
-DWITH_AUTHENTICATION_LDAP=OFF \
-DWITH_DEBUG=1 \
-DCMAKE_BUILD_TYPE=Debug \
&& sudo make -j2 VERBOSE=1 && sudo make install

报错日志没找到，但是当时应该是make的时候报的错，错误原因就是那两个断言检查不成功，
PFS_DD_VERSION 和 IS_DD_VERSION写入的是定值，我应该也是下载的release的最新版，可能是我系统的问题吧，或者说那两个值就和系统有关系，我没仔细关注这一点

**Comment by GreatSQL** [comment]
你下载了最新版本的代码，那么匹配的版本号就应该是8.0.32，编译参数中这几个也要跟着改成下面这样
```
-DMAJOR_VERSION=8
-DMINOR_VERSION=0
-DPATCH_VERSION=32
```

原来的参数值是指8.0.25版本的意思，请修改后再尝试看看。

**Comment by physicszq** [comment]
嗯嗯，谢谢



---Original---
From: ***@***.***&gt;
Date: Mon, Apr 22, 2024 08:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GreatSQL/GreatSQL] The newest version  v8.0.32.25 facescompiling problem (Issue #6)




 
你下载了最新版本的代码，那么匹配的版本号就应该是8.0.32，编译参数中这几个也要跟着改成下面这样
 -DMAJOR_VERSION=8 -DMINOR_VERSION=0 -DPATCH_VERSION=32  
原来的参数值是指8.0.25版本的意思，请修改后再尝试看看。

**Comment by GreatSQL** [comment]
> 嗯嗯，谢谢
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Apr 22, 2024 08:27 AM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [GreatSQL/GreatSQL] The newest version v8.0.32.25 facescompiling problem (Issue #6) 你下载了最新版本的代码，那么匹配的版本号就应该是8.0.32，编译参数中这几个也要跟着改成下面这样 -DMAJOR_VERSION=8 -DMINOR_VERSION=0 -DPATCH_VERSION=32 原来的参数值是指8.0.25版本的意思，请修改后再尝试看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

麻烦再确认下，如果没问题那我就把这个issue关了哈

**Comment by physicszq** [comment]
主要是按照我之前的修改已经编译成功了，再编译一次确实比较耗时，这个等我有时间再编译一次吧
，先关了吧

---Original---
From: ***@***.***&gt;
Date: Tue, Apr 23, 2024 09:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GreatSQL/GreatSQL] The newest version  v8.0.32.25 facescompiling problem (Issue #6)




  
嗯嗯，谢谢
 …
 ---Original--- From: @.&gt; Date: Mon, Apr 22, 2024 08:27 AM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [GreatSQL/GreatSQL] The newest version v8.0.32.25 facescompiling problem (Issue #6) 你下载了最新版本的代码，那么匹配的版本号就应该是8.0.32，编译参数中这几个也要跟着改成下面这样 -DMAJOR_VERSION=8 -DMINOR_VERSION=0 -DPATCH_VERSION=32 原来的参数值是指8.0.25版本的意思，请修改后再尝试看看。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
麻烦再确认下，如果没问题那我就把这个issue关了哈
