### ISSUE TITLE
作者你好，请问针对数据库大批量并发更新又做性能提升嘛？mysql大批量并发更新数据库的时候性能不是很理想

### ISSUE THREAD

**Issue by cfy3133** [greatsql/GreatSQL#8]

**Comment by GreatSQL** [comment]
GreatSQL是有针对InnoDB事务性能做了优化，也请详细说下什么样的应用场景吗，以及遇到什么问题。
欢迎来我们社区发帖讨论 https://greatsql.cn/forum.php
