### ISSUE TITLE
【咨询】请问一下up，debian10和debian12支持吗？谢谢啊。

### ISSUE THREAD

**Issue by taurusduan** [greatsql/GreatSQL#9]
请问一下up，debian10和debian12支持吗？谢谢啊。

**Comment by GreatSQL** [comment]
您好，理论上应该是支持的，需要在这些平台下用源码编译二进制包
编译方法可参考 https://greatsql.cn/docs/8.0.32-25/4-install-guide/6-install-with-source-code.html
如果还有其他问题可以来我们社区论坛发帖交流 https://greatsql.cn/forum.php
